substitutions:
  name: esphome-web-5e2c58
  friendly_name: Led_1

esphome:
  compile_process_limit: 1
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: dev


            
      

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "LuceMobileCaffe"
    password: "Fanfo1122"

captive_portal:

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO16
    num_leds: 10
    name: "Led Caffe"
    id: Led_Caffe
    rgb_order: GRB
    effects:
      - random:
      - pulse:
      - strobe:
      - flicker:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO18
    num_leds: 6
    name: "All_Led_stampanti"
    id: strip
    rgb_order: GRB
    effects:
      - random:
      - pulse:
      - strobe:
      - flicker:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
        
  - platform: partition
    name: "Led_Stampante_1"
    id: LedStampante1
    segments:
      - id: strip
        from: 0
        to: 0
    effects:
      - random:
      - pulse:
      - strobe:
      - flicker:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
  - platform: partition
    name: "Led_stampante_2"
    id: LedStampante2
    segments:
      - id: strip
        from: 1
        to: 1
    effects:
      - random:
      - pulse:
      - strobe:
      - flicker:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
  - platform: partition
    name: "Led_stampante_3"
    id: LedStampante3
    segments:
      - id: strip
        from: 2
        to: 2
    effects:
      - random:
      - pulse:
      - strobe:
      - flicker:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
  - platform: partition
    name: "Led_stampante_4"
    id: LedStampante4
    segments:
      - id: strip
        from: 3
        to: 3
    effects:
      - random:
      - pulse:
      - strobe:
      - flicker:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
  - platform: partition
    name: "Led_stampante_5"
    id: LedStampante5
    segments:
      - id: strip
        from: 4
        to: 4
    effects:
      - random:
      - pulse:
      - strobe:
      - flicker:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
  - platform: partition
    name: "Led_stampante_6"
    id: LedStampante6
    segments:
      - id: strip
        from: 5
        to: 5
    effects:
      - random:
      - pulse:
      - strobe:
      - flicker:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:







